{
 "title": "Main Dash",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Freezer Temperature  ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  TIME AS \"time\",\n  temp1_db,\n  temp2_db,\n  temp3_db,\n  temp4_db\nFROM feather_m0_sensors\nWHERE\n  $__timeFilter(TIME)\nORDER BY TIME"
    }
   ]
  },
  {
   "title": "Freezer Humidity ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\n  TIME AS \"time\",\n  humi1_db,\n  humi2_db,\n  humi3_db,\n  humi4_db\nFROM feather_m0_sensors\nWHERE\n  $__timeFilter(TIME)\nORDER BY TIME"
    }
   ]
  },
  {
   "title": "Freezer Temperature  ",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  TIME AS \"time\",\n  temp1_db,\n  temp2_db,\n  temp3_db,\n  temp4_db\nFROM feather_m0_sensors\nWHERE\n  $__timeFilter(TIME)\nORDER BY TIME"
    }
   ]
  },
  {
   "title": "Freezer Humidity ",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  TIME AS \"time\",\n  humi1_db,\n  humi2_db,\n  humi3_db,\n  humi4_db\nFROM feather_m0_sensors\nWHERE\n  $__timeFilter(TIME)\nORDER BY TIME"
    }
   ]
  },
  {
   "title": "Main Room",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  TIME AS \"time\",\n  tempRoom_db,\n  humiRoom_db\nFROM feather_m0_sensors\nWHERE\n  $__timeFilter(TIME)\nORDER BY TIME"
    }
   ]
  }
 ]
}